In [1]:
from altaipony.lcio import from_mast
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.6f' % x)
%matplotlib inline

In [2]:
df = pd.read_csv("C:\Vs_code_projects\mdwarf_flares\epic_catalogue.csv")

<>:1: DeprecationWarning: invalid escape sequence '\V'
<>:1: DeprecationWarning: invalid escape sequence '\V'
C:\Users\thoma\AppData\Local\Temp\ipykernel_34860\3456439302.py:1: DeprecationWarning: invalid escape sequence '\V'
  df = pd.read_csv("C:\Vs_code_projects\mdwarf_flares\epic_catalogue.csv")


In [7]:
np.where(df['Highest percentage increase'] > 100)

(array([  33,  261,  485,  570,  595,  630,  703,  914, 1266, 1422, 1517,
        1850, 1907, 2043, 2116, 2142, 2206, 2455, 2490, 2615, 2723, 2775,
        2816, 2836, 3023, 3026, 3028, 3042, 3084, 3086, 3135, 3159, 3195,
        3198, 3210, 3224], dtype=int64),)

In [5]:
len(large[0])

36

In [5]:
np.where(df['Lowest percentage increase'] < 0)

(array([2142], dtype=int64),)

In [6]:
np.where(df['Highest percentage increase'] > 100000)

(array([3042], dtype=int64),)